job: build
image: docker.softcreate.de/eternalconcert/builder-default
stages:
  - name: build
    run: |
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends g++ flex bison
      lex src/patterns.l
      bison -d -o y.tab.c src/grammar.y
      g++ -Wno-free-nonheap-object lex.yy.c y.tab.c $(find src/ -name "*.cpp") -o tea --static -D BUILDNO=$BUILDER_RUN
      ./tea tests/tests_basics.t
      ./tea tests/tests_cast.t
      ./tea tests/tests_comparisons.t
      ./tea tests/tests_conditions.t
      ./tea tests/tests_functions.t
      ./tea tests/tests_imports.t
      ./tea tests/tests_teahouse_imports.t
      ./tea tests/tests_loops.t
      ./tea tests/tests_operations.t
      cp tea /out/
  - name: build-website
    run: |
      cp /out/tea tea
      cd example
      ./install.deps.t
      mkdir -p build/static
      ./app.t
      tar -czvf build.tar.gz build
      cp build.tar.gz /out/build.tar.gz
