job: build
image: docker.softcreate.de/eternalconcert/builder-default
stages:
  - name: build
    run: |
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends g++ flex bison
      lex src/patterns.l
      bison -d -o y.tab.c src/grammar.y
      g++ -Wno-free-nonheap-object lex.yy.c y.tab.c $(find src/ -name "*.cpp") -o tea --static -D BUILDNO=$BUILDER_RUN
      ./tea common/testrunner.t --skip=tests/tests_http.t
      cp tea /out/
  - name: build-website
    run: |
      cp /out/tea tea.bin
      cp /out/tea example/templates/static/tea.bin
      ln -s /out/tea /app/tea.bin

      docker login docker.softcreate.de --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      cd example
      ../tea.bin --install
      export DEBIAN_FRONTEND=noninteractive
      docker build --build-arg BUILD_NO=$BUILDER_RUN -f ../Dockerfile .. -t docker.softcreate.de/eternalconcert/tea2:$BUILDER_RUN
      docker tag docker.softcreate.de/eternalconcert/tea2:$BUILDER_RUN docker.softcreate.de/eternalconcert/tea2:$BUILDER_RUN
      docker tag docker.softcreate.de/eternalconcert/tea2:$BUILDER_RUN docker.softcreate.de/eternalconcert/tea2:latest
      docker push docker.softcreate.de/eternalconcert/tea2:$BUILDER_RUN
      docker push docker.softcreate.de/eternalconcert/tea2:latest
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
