job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
stages:
  - name: dependencies
    run: |
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends g++ flex bison
      lex src/patterns.l
      yacc -d src/grammar.y
      g++ lex.yy.c y.tab.c $(find src/ -name "*.cpp") -o tea --static -D BUILDNO=$BUILDER_RUN
  - name: tests
    run:
      run: |
        ./tea tests/tests_basics.t
        ./tea tests/tests_operations.t
        ./tea tests/tests_comparisons.t
        ./tea tests/tests_conditions.t
        ./tea tests/tests_loops.t
