name: Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get install lex bison lcov
    - name: Build
      run: |
        CPPSOURCES = $(shell find src/ -name "*.cpp")
       	lex src/patterns.l
	      yacc -d src/grammar.y
        g++ lex.yy.c y.tab.c $(CPPSOURCES) -o tea --static
    - name: Test
      run: |
        ./tea tests/tests.t
