name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install flex bison lcov
    - name: Build
      run: |
        lex src/patterns.l
        yacc -d src/grammar.y
        g++ lex.yy.c y.tab.c $(find src/ -name "*.cpp") -o tea --static -D BUILDNO=0
        cp tea /out/
    - name: Test
      run: |
        ld /out/
        /out/tea tests/tests_basics.t
        /out/tea tests/tests_operations.t
        /out/tea tests/tests_comparisons.t
        /out/tea tests/tests_conditions.t
        /out/tea tests/tests_loops.t
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: tea
        path: tea
